#https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Python
      uses: actions/checkout@v4
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.5"
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check . --fix
        ruff format . 
    - name: Test with pytest
      run: |
        pip install pytest 
        pytest tests.py 
    - name: Test with Tox
      run: |
        pip install tox
        tox -e py
           
#ruff --output-format=github .

#future implementazioni:
# - dipendenze
# - artefatto
# - package registry